AllCops:
  Exclude:
    - "spec/**/*"
    - "examples/**/*"
    - "support/**/*"
    - "wayfarer.gemspec"
    - "examples"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 10
