gems:
  - bourbon
  - neat

markdown: kramdown
sass:
  style: :compressed

kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

title: Wayfarer

categories:
  - Basics
  - Routing
  - Selenium
  - Contributing
